sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - nvm install 14
  - pip install tox
script: tox -e py,lint,coveralls
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
